### ISSUE TITLE
Bug: Button animation too slow

### ISSUE THREAD

**Issue by AgilePlaya** [RaghavParashar1/RaghavParashar1.github.io#2]
# **Description**
This is the problem in question:

<img src="https://user-images.githubusercontent.com/60707646/122641143-fab11500-d120-11eb-9b1f-0af69d62439b.gif" alt="Raghav_button_01" width="341px" height="216px">

If the mouse cursor is moving too fast, this seems to be a major issue as when the moves over it, things are not very readable.

# **To Reproduce**
Just hover over any of the buttons to notice it yourself.

# **Expected behavior**
The buttons should be more snappy and less sluggish

I reduced the transition duration from 0.6s to 0.3s, effectively doubling the speed to make it look something like this:

<img src="https://user-images.githubusercontent.com/60707646/122641203-5ed3d900-d121-11eb-9591-a97f95dd5559.gif" alt="Raghav_button_01" width="341px" height="216px">

This to me seems much more responsive as a button.

**Comment by RaghavParashar1** [comment]
Changes completed
