### ISSUE TITLE
Feature Request: Subtle animation for the images

### ISSUE THREAD

**Issue by AgilePlaya** [RaghavParashar1/RaghavParashar1.github.io#3]
# **Description**
When the page loads, the images just appears, which is functional, but not very good looking.

# **Suggested Modification**
What I would suggest is adding `onload="this.className='animate img-fluid'" ` to the <img> like so:
```
<img onload="this.className='animate img-fluid'" src="<!--file-location-->" alt="Banner-Image" class="img-fluid">
```

After this, you will also need to add some code for the animate class in css.
This is what I tried:
```
.animate{
    opacity: 1;
    -webkit-transition: opacity 1s ease-in-out;
    -moz-transition: opacity 1s ease-in-out;
    -ms-transition: opacity 1s ease-in-out;
    -o-transition: opacity 1s ease-in-out;
    transition: opacity 1s ease-in-out;
}
img{opacity: 0}
```

# **Comparision**

### This is the before:

<img src="https://user-images.githubusercontent.com/60707646/122641556-b8d59e00-d123-11eb-8ae0-2802ac3137df.gif" alt="Raghav_button_01" width="521px" height="268px">

### This is the after

<img src="https://user-images.githubusercontent.com/60707646/122641590-f3d7d180-d123-11eb-9be6-f3c01e1238b9.gif" alt="Raghav_button_01" width="521px" height="268px">

**Comment by RaghavParashar1** [comment]
Changes done
